Repository bytedance/byteir, pull requests merged in 2023-09, with the labels that each got.

#51 [ci] add torch frontend ci
  .github/workflows/compiler-and-runtime-build.yml
  .github/workflows/torch-frontend-ci.yml
  scripts/frontends/torch-frontend/build_and_test.sh
  scripts/frontends/torch-frontend/envsetup.sh
Labels: enhancement

#57 [Doc] Improve linalg doc
  compiler/doc/attention.md
  compiler/doc/linalg.md
Labels: documentation

#69 Fix explicit instantiation of template functions
  compiler/lib/Dialect/mhlo/Util/Util.cpp
Labels: bug
