Repository bytedance/byteir, pull requests merged in 2024-02, with the labels that each got.

#111 [ONNX] fix onnx convTranspose output_padding and others
  frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.cpp
  frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.td
  frontends/onnx-frontend/onnx-frontend/test/of_rewrite_to_custom_call.mlir
  frontends/onnx-frontend/test/ops/test_nn.py
  frontends/onnx-frontend/third_party/patches/OnnxMlirConvTranspose.patch
  frontends/onnx-frontend/third_party/patches/OnnxMlirResizeV13ShapeInfer.patch
Labels: enhancement, sync

#118 [tf-frontend] build ace_dialect using external source code
  frontends/tf-frontend/WORKSPACE
  frontends/tf-frontend/byteir/BUILD
  frontends/tf-frontend/byteir/Dialect/Ace/AceBase.td
  frontends/tf-frontend/byteir/Dialect/Ace/AceDialect.cpp
  frontends/tf-frontend/byteir/Dialect/Ace/AceDialect.h
  frontends/tf-frontend/byteir/Dialect/Ace/AceOps.td
  frontends/tf-frontend/byteir/ace.BUILD
  frontends/tf-frontend/byteir/workspace.bzl
  frontends/tf-frontend/tf_mlir_ext/transforms/BUILD
  frontends/tf-frontend/tools/BUILD
Labels: enhancement

#110 [torch-frontend] add more ops for lowering to ccl dialect
  compiler/dialects/include/byteir/Dialect/Ccl/IR/CclOps.td
  compiler/dialects/lib/Dialect/Ccl/IR/CclOps.cpp
  compiler/lib/Dialect/Ccl/TransformOps/CclTransformOps.cpp
  compiler/lib/Dialect/Linalg/TransformOps/LinalgExtTransformOps.cpp
  compiler/lib/Utils/TileUtils.cpp
  compiler/test/Dialect/Ccl/ccl_move_down.mlir
  compiler/test/Dialect/Ccl/decompose_all_reduce.mlir
  compiler/test/Dialect/Ccl/invalid.mlir
  compiler/test/Dialect/Ccl/ops.mlir
  frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCcl.cpp
  frontends/torch-frontend/torch-frontend/lib/Pipelines/Pipelines.cpp
  frontends/torch-frontend/torch-frontend/python/CMakeLists.txt
  frontends/torch-frontend/torch-frontend/python/test/test_ccl.py
  frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py
  frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
  frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCcl.mlir
Labels: enhancement

#125 [torch-frontend] Add broadcast collective operators and support compile torch.compiled model.
  compiler/dialects/include/byteir/Dialect/Ccl/IR/CclOps.td
  compiler/dialects/lib/Dialect/Ccl/IR/CclOps.cpp
  frontends/torch-frontend/third_party/patches/communication_op.patch
  frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCcl.cpp
  frontends/torch-frontend/torch-frontend/python/test/test_ccl.py
  frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py
  frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
  frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCcl.mlir
Labels: enhancement

#124 [torch-frontend] add test for collective operators
  frontends/torch-frontend/requirements.txt
  frontends/torch-frontend/torch-frontend/python/test/test_attn_rewrite.py
  frontends/torch-frontend/torch-frontend/python/test/test_ccl.py
  frontends/torch-frontend/torch-frontend/python/test/utils.py
  frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
Labels: enhancement

#129 [doc] fix license format.
  LICENSE
Labels: documentation

#130 [HLO] do not fusion single reshape in aggressive fusion and bump versions
  compiler/lib/Dialect/mhlo/Transforms/HloAggressiveFusion.cpp
  compiler/python/version.txt
  compiler/test/Dialect/Mhlo/transforms/aggressiveFusion.mlir
  frontends/torch-frontend/torch-frontend/python/version.txt
  runtime/VERSION_NUMBER
Labels: enhancement, sync

#133 [doc] change contributors.md to contributing.md
  CONTRIBUTING.md
Labels: documentation

#135 [github] Update issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: enhancement
