Repository bytedance/byteir, pull requests merged in 2024-04, with the labels that each got.

#176 [torch-frontend] enable building torch-frontend without jit_ir_importer dependency
  frontends/torch-frontend/CMakeLists.txt
  frontends/torch-frontend/TorchMLIR.cmake
  frontends/torch-frontend/scripts/build_and_test.sh
  frontends/torch-frontend/torch-frontend/python/CMakeLists.txt
  frontends/torch-frontend/torch-frontend/python/setup.py
  runtime/lib/backends/cpu/device/llvm/jit.cc
  runtime/lib/backends/cpu/providers/default/llvm/jit.cc
Labels: enhancement, sync

#172 [compiler] add byre::ComputeOnTensorOp with DestinationStyle
  compiler/include/byteir/Conversion/Passes.td
  compiler/include/byteir/Dialect/Byre/ByreDialect.h
  compiler/include/byteir/Dialect/Byre/ByreOps.td
  compiler/include/byteir/Dialect/mhlo/Util/ShapeInferUtil.h
  compiler/include/byteir/Dialect/mhlo/Util/Util.h
  compiler/lib/Conversion/FuncToByre/CMakeLists.txt
  compiler/lib/Conversion/FuncToByre/FuncToByre.cpp
  compiler/lib/Conversion/HloToByreTensor/HloToByreTensor.cpp
  compiler/lib/Conversion/ToByre/ToByre.cpp
  compiler/lib/Dialect/Byre/Transforms/BufferizableOpInterfaceImpl.cpp
  compiler/lib/Dialect/mhlo/Transforms/ShapeReification.cpp
  compiler/lib/Dialect/mhlo/Util/ShapeInferUtil.cpp
  compiler/lib/Dialect/mhlo/Util/Util.cpp
  compiler/test/Conversion/FuncToByre/func_to_byre_tensor.mlir
  compiler/test/Conversion/HloToByreTensor/compute_ops.mlir
  compiler/test/Dialect/Byre/bufferize.mlir
  compiler/test/Dialect/Byre/tensor_ops.mlir
  compiler/test/E2E/MLPInference/4_bufferize_opt.mlir
  compiler/test/E2E/ResNet18/BW/4_bufferize_opt.mlir
  compiler/test/E2E/ResNet18/FW/4_bufferize_opt.mlir
  compiler/test/E2E/ResNet18/Whole/4_bufferize_opt.mlir
Labels: enhancement

#181 [compiler] use BYRE as serialization producer string
  compiler/lib/CAPI/Translation.cpp
Labels: enhancement

#180 [onnx] keep shape for static bs
  frontends/onnx-frontend/onnx-frontend/src/Compiler/OFCompilerUtils.cpp
Labels: enhancement

#184 [*] update README and some examples
  README-zh_cn.md
  README.md
  frontends/torch-frontend/examples/inference/infer_resnet.py
  frontends/torch-frontend/examples/inference/infer_tinybert.py
Labels: documentation, enhancement

#187 [compiler] support dynamic shape for concatOp conversion
  compiler/lib/Conversion/HloToByreTensor/HloToByreTensor.cpp
  compiler/test/Conversion/HloToByreTensor/compute_ops.mlir
Labels: enhancement

#188 [compiler] support dynamic shape for memrefcopyToLinalg
  compiler/lib/Conversion/ToLinalg/MemrefCopyToLinalg.cpp
  compiler/test/Conversion/ToLinalg/memrefcopyToLinalg.mlir
Labels: enhancement

#193 [tf-frontend] support stop after convert to tf dialect
  frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.cc
  frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.h
  frontends/tf-frontend/tf_mlir_ext/pipelines/passes.td
  frontends/tf-frontend/tools/tf_frontend_main.cc
Labels: enhancement

#201 [onnx] remove assert keepdims for argmax/argmin
  frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.cpp
Labels: enhancement

#202 [compiler] bufferize computeOnTensor with valid layout buffer
  compiler/lib/Dialect/Byre/Transforms/BufferizableOpInterfaceImpl.cpp
  compiler/test/Dialect/Byre/bufferize.mlir
Labels: enhancement

#206 [runtime] add custom_call byteir.repeat op_kernel on cpu
  runtime/lib/backends/cpu/providers/default/cpu_provider.cc
  runtime/lib/backends/cpu/providers/default/custom_call/repeat.cc
  runtime/lib/backends/cpu/providers/default/custom_call/repeat.h
  runtime/test/backends/cpu/providers/default/kernel/repeat_test.cc
  runtime/test/common/models.cc
  runtime/test/include/brt/test/common/models.h
Labels: enhancement

#198 [compiler] support cluster dependence analysis to fix illegal fusion
  compiler/include/byteir/Analysis/OpDependence.h
  compiler/include/byteir/Dialect/mhlo/Util/FusionUtil.h
  compiler/lib/Analysis/OpDependence.cpp
  compiler/lib/Dialect/mhlo/Util/FusionUtil.cpp
  compiler/test/Dialect/Mhlo/transforms/elementFusion.mlir
Labels: enhancement

#224 [compiler] add cpu target compiler
  compiler/python/byteir/compile.py
  compiler/python/byteir/tools/compiler.py
  compiler/python/test/api/test_py_api.py
Labels: enhancement

#226 [runtime] fix bind arg
  runtime/lib/backends/cpu/device/cpu_work_queue.cc
  runtime/lib/core/context/execution_frame.cc
  runtime/test/backends/cpu/providers/default/request_context_test.cc
  runtime/test/backends/cuda/providers/default/request_context_test.cc
Labels: bug
